### ISSUE TITLE
Error with 'require' in crypto/ed25519.js file

### ISSUE THREAD

**Issue by marcobono** [HarmonicLabs/plu-ts#11]
I was following the documentation for the Hello plu-ts project set up and did the following steps:
- cloned the boilerplate project with `git clone https://github.com/HarmonicLabs/plu-ts-starter.git`
- run `npm i`

and this is what i have in my package json:
```
  "dependencies": {
    "@harmoniclabs/plu-ts": "^0.3.0-dev9"
  },
  "devDependencies": {
    "tsc-alias": "^1.7.1",
    "typescript": "^4.8.4"
  }
```

-  run `npm run start`, the build succeeds without any problem but when attempting to run  `node dist/index.js` I get the following error:

```
C:\Users\marco\DEV\plu_ts\plu-ts-starter\node_modules\@harmoniclabs\plu-ts\dist\crypto\ed25519.js:5
var ed25519_1 = require("@noble/ed25519");
                ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\marco\DEV\plu_ts\plu-ts-starter\node_modules\@noble\ed25519\index.js from C:\Users\marco\DEV\plu_ts\plu-ts-starter\node_modules\@harmoniclabs\plu-ts\dist\crypto\ed25519.js not supported.
Instead change the require of index.js in C:\Users\marco\DEV\plu_ts\plu-ts-starter\node_modules\@harmoniclabs\plu-ts\dist\crypto\ed25519.js to a dynamic import() which is available in all CommonJS modules.     
    at Object.<anonymous> (C:\Users\marco\DEV\plu_ts\plu-ts-starter\node_modules\@harmoniclabs\plu-ts\dist\crypto\ed25519.js:5:17)
    at Object.<anonymous> (C:\Users\marco\DEV\plu_ts\plu-ts-starter\node_modules\@harmoniclabs\plu-ts\dist\crypto\index.js:19:14)    at Object.<anonymous> (C:\Users\marco\DEV\plu_ts\plu-ts-starter\node_modules\@harmoniclabs\plu-ts\dist\onchain\CEK\BnCEK\index.js:49:16)
    at Object.<anonymous> (C:\Users\marco\DEV\plu_ts\plu-ts-starter\node_modules\@harmoniclabs\plu-ts\dist\onchain\CEK\Machine\index.js:24:15)
    at Object.<anonymous> (C:\Users\marco\DEV\plu_ts\plu-ts-starter\node_modules\@harmoniclabs\plu-ts\dist\onchain\CEK\index.js:18:17)
    at Object.<anonymous> (C:\Users\marco\DEV\plu_ts\plu-ts-starter\node_modules\@harmoniclabs\plu-ts\dist\onchain\pluts\Term\index.js:10:13)
    at Object.<anonymous> (C:\Users\marco\DEV\plu_ts\plu-ts-starter\node_modules\@harmoniclabs\plu-ts\dist\onchain\pluts\PTypes\PStruct\pmatch\index.js:36:14)
    at Object.<anonymous> (C:\Users\marco\DEV\plu_ts\plu-ts-starter\node_modules\@harmoniclabs\plu-ts\dist\onchain\pluts\PTypes\PStruct\index.js:17:14)
    at Object.<anonymous> (C:\Users\marco\DEV\plu_ts\plu-ts-starter\node_modules\@harmoniclabs\plu-ts\dist\onchain\pluts\PTypes\index.js:17:14)
    at Object.<anonymous> (C:\Users\marco\DEV\plu_ts\plu-ts-starter\node_modules\@harmoniclabs\plu-ts\dist\onchain\pluts\index.js:18:14)
    at Object.<anonymous> (C:\Users\marco\DEV\plu_ts\plu-ts-starter\node_modules\@harmoniclabs\plu-ts\dist\onchain\index.js:17:14)
    at Object.<anonymous> (C:\Users\marco\DEV\plu_ts\plu-ts-starter\node_modules\@harmoniclabs\plu-ts\dist\index.js:17:14) {
  code: 'ERR_REQUIRE_ESM'
}

```

Environment:
I am currently on Windows using Node.js v19.6.1

**Comment by michele-nuzzi** [comment]
Wow thank you for catching this!

Will fix it today; meanwhile changing `0.3.0-dev9` to `0.3.0-dev7` and running angain `npm install` should fix the issue.

Will let you know as soon as version `0.3.0-dev10` is released with a fix!

**Comment by michele-nuzzi** [comment]
the github repository `plu-ts-starter` has been updated as described until `0.3.0-dev10` is released

**Comment by marcobono** [comment]
I confirm that changing the dependency to version `0.3.0-dev7` solves the issue, thanks for the immediate support

**Comment by michele-nuzzi** [comment]
@marcobono version `0.3.0-dev10` just released and `plu-ts-starter` updated;

I repeated the process as you described and the issue seems to be solved; I'll wait some time for your confirmation if you can before closing the issue.

**Comment by marcobono** [comment]
@michele-nuzzi yes, i updated the dep to version `0.3.0-dev10` and the script runs without throwing errors 👏

**Comment by michele-nuzzi** [comment]
Awesome, thanks a lot for opening the issue!
